### ISSUE TITLE
More digits for percents in tables

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Cruncher#45]
![image](https://user-images.githubusercontent.com/8301092/95663802-1be05100-0b10-11eb-9e92-f1e3746ede7e.png)

It would be helpful if tax rates were given two more digits. In this example, for instance, the base payroll tax marginal rate is shown as 0.14, whereas 0.14## would be useful. One more digit would also be helpful, but I think two would be best so that percents, when written as such, align with the dollar figures.

**Comment by Peter-Metz** [comment]
Thanks for opening this issue @MattHJensen. I've opened #46 to convert MTR's from decimals to percentages.

**Comment by Peter-Metz** [comment]
Resolved by #46
